# Generated by Django 4.1.3 on 2022-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcodes',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationcodes',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
